services:
  app: &app
    build:
      context: .
      dockerfile: ./.docker/development/Dockerfile
      target: dev
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - db-init:/db-init
      - ./bin/bundle-binstub:/usr/src/app/bin/bundle
    depends_on:
      - pg
      - cache
      - mail
      - worker
    environment:
      - PORT=3000
      - RAILS_DB_HOST=pg
      - RAILS_ENV=development
      - RAILS_MEMCACHED_HOST=cache
      - SKIP_MEMCACHE_CHECK=true
      - RAILS_MAIL_DELIVERY_CONFIG=address:mail,port:1025
      #- RAILS_DB_NAME=decidim_zuerich_production
    ports:
      - 3000:3000
    command: bundle exec puma
    entrypoint: ./.docker/development/entrypoint.sh
    tty: true
    stdin_open: true
  pg:
    image: postgis/postgis:14-3.3-alpine
    environment:
      - POSTGRES_USER=decidim_zuerich
      - POSTGRES_PASSWORD=dN5GH8y3lX
      - POSTGRES_DB=decidim_zuerich_development
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./.docker/00-prepare-for-prod-dump.sql:/docker-entrypoint-initdb.d/00-prepare-for-prod-dump.sql
      # - ./.docker/database-init.sql:/docker-entrypoint-initdb.d/database-init.sql
  cache:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]
  webpack:
    <<: *app
    depends_on: []
    ports:
      - 3035:3035
    entrypoint: ./.docker/development/webpack-entrypoint.sh
    command: [ 'bin/webpack-dev-server' ]

  mail:
    image: schickling/mailcatcher:latest
    ports:
      - '1080:1080'
  worker:
    <<: *app
    depends_on: []
    ports: []
    entrypoint: []
    command: [ rake, 'jobs:work' ]

volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
  db-init: {}
